// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yqqkhvrgiclvfxobnnhw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlxcWtodnJnaWNsdmZ4b2Jubmh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ5NDMzNDIsImV4cCI6MjA5MDUxOTM0Mn0.OzeNhQ5pmiJfPFGzJ1upu4OmRA20uF0sgonRrTXdGHo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
